project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "{{< var course.number >}} - {{< var course.semester >}}"
  description: "Homepage for {{< var course.number >}}, {{< var course.title >}}, at Rice University, {{< var course.semester >}}."
  site-url: https://jdossgollin.github.io/ceve543-f23
  repo-url: https://github.com/jdossgollin/ceve543-f23
  repo-actions: [edit, issue]
  open-graph: true

  page-footer:
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source on {{< fa brands github >}} GitHub]({{< var course.github >}})

    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}}  by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}).
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

  sidebar:
    style: docked
    align: center
    logo: _assets/logos/Rice_Logo_280_Blue.svg
    title: "{{< var course.number >}}"
    search: true
    tools: 
      - icon: github
        href: "{{var course.github}}"
        text: "Github Repository"
      - icon: journal-check
        href: https://canvas.rice.edu
        text: "Canvas"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: schedule.qmd
        text: Schedule
      - href: syllabus.qmd
        text: Syllabus
      - text: "Tools Setup"
        href: setup.qmd
      - text: "FAQ"
        href: faq.qmd
      - section: "Tutorials"
        contents:
          - href: tutorials/julia-basics.qmd
            text: Julia Basics
          - href: tutorials/julia-plots.qmd
            text: Making Plots
          - href: tutorials/latex-notebook.qmd
            text: Math in Notebooks
      - section: Resources
        contents:
          - href: resources/julia.qmd
            text: Julia
          - href: resources/github.qmd
            text: GitHub
          - href: resources/markdown.qmd
            text: Markdown


format:
  html:
    theme: 
      [simplex, sass/theme.scss]
    mainfont: "Atkinson Hyperlegible"
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: margin
    citation-location: margin
    code-annotations: select
    html-math-method: mathjax
    include-in-header: mathjax-config.html

bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl

jupyter: julia-1.9
execute:
  freeze: auto  