project:
  type: website
  preview:
    port: 5543

render:
  - "*"         # Render all files
  - "!CLAUDE.md"  # EXCEPT this file
  - "!instructor"
  - "!instructor/"

website:
  page-navigation: true
  title: CEVE 543 - Fall 2025
  description: "Homepage for {{< var course.number >}}, {{< var course.title >}}, at Rice University, {{< var course.semester >}}."
  site-url: https://ceve543.github.io/
  repo-url: "{{< var repo-url >}}"
  repo-actions: [issue]
  open-graph: true
  
  navbar:
    logo: _assets/logos/Rice_Logo_280_Blue.svg
    title: "CEVE 543"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: assignments.qmd
        text: Assignments
      - href: labs.qmd
        text: Labs
    right:
      - icon: book
        href: "{{< var textbook-url >}}"
        text: "Textbook"
      - icon: journal-check
        href: https://canvas.rice.edu/courses/82127
        text: "Canvas"

  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var course.copyright_year >}} [James Doss-Gollin](https://jdossgollin.github.io)</span>
      <span class="faux-block">
    center: |
      All content licensed under [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY-NC 4.0](/license.qmd)</span>

    right: |
      <span class="faux-block">Made with Julia and [Quarto](https://quarto.org/).</span>
      <span class="faux-block">[View the source on {{< fa brands github >}} GitHub]({{< var repo-url >}})</span>

      

echo: true

format:
  # customization for HTML documents (i.e., the website)
  html:
    theme: simplex
    toc: true
    copy-code: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: document
    citations-hover: true
    html-math-method: katex
    date-format: "ddd., MMM. D"
    code-line-numbers: true
    code-overflow: wrap
    code-annotations: hover
    code-copy: true
  typst:
    margin: 
      top: 1in
      bottom: 1in
      left: 1in
      right: 1in
    fontsize: 11pt

# references
bibliography: references.bib
biblio-style: _assets/references/american-geophysical-union.csl


# execution options
execute:
  freeze: auto  
  cache: true
