project:
  type: website
  preview:
    port: 4201
  render:
    - "*.qmd"
    - "!instructor-notes.qmd"

website:
  page-navigation: true
  title: CEVE 543 - Fall 2025
  description: "Homepage for {{< var course.number >}}, {{< var course.title >}}, at Rice University, {{< var course.semester >}}."
  site-url: https://ceve543.github.io/
  repo-url: "{{< var repo-url >}}"
  repo-actions: [edit, issue]
  open-graph: true

  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var course.copyright_year >}} [James Doss-Gollin](https://jdossgollin.github.io)</span>
      <span class="faux-block">
    center: |
      All content licensed under [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY-NC 4.0](/license.qmd)</span>

    right: |
      <span class="faux-block">Made with Julia and [Quarto](https://quarto.org/).</span>
      <span class="faux-block">[View the source on {{< fa brands github >}} GitHub]({{< var repo-url >}})</span>

  sidebar:
    style: docked
    align: center
    logo: _assets/logos/Rice_Logo_280_Blue.svg
    title: "{{< var course.number >}}"
    search: true
    tools: 
      - icon: github
        href: "{{var course.github}}"
        text: "Github Repository"
      - icon: journal-check
        href: https://canvas.rice.edu
        text: "Canvas"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - text: <hr>
      - href: license.qmd

      

echo: true

format:
  # customization for HTML documents (i.e., the website)
  html:
    theme: 
      [simplex, _assets/sass/theme.scss]
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: document
    citations-hover: true
    code-annotations: hover
    html-math-method: mathjax
    include-in-header: mathjax-config.html
    date-format: "ddd., MMM. D"

# references
bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl


# execution options
execute:
  freeze: auto  
  cache: true

auto-agenda:
  bullets: numbered
  heading: Today

engines: ['julia']