---
format:
  html:
    toc-depth: 3
    title: Syllabus
  pdf:
    documentclass: article
    fontsize: 11pt
    geometry:
      - margin=1in  
    include-in-header:
      text: |
        \renewcommand\toprule[2]\relax
        \renewcommand\bottomrule[2]\relax
    filters:
      - _assets/filters/columns-to-tables.lua
    title: "{{< var course.number >}} ({{< var course.title >}}) Syllabus"
    subtitle: "{{< var course.semester >}}"
  docx:
    toc: true
    toc-depth: 2
    number-sections: false
---

## Course Overview

This course covers the use of tools from data science (statistics, machine learning, and programming) to model climate hazards such as floods and droughts. Through hands-on programming assignments based on state-of-the-art published research, students will learn to apply methods to real-world problems with a strong emphasis on probabilistic methods and uncertainty quantification.

## Course Information
:::: {.columns .course-details}

::: {.column width="30%"}
### Instructor

* {{< fa sharp user title="Name" >}} [[{{< var instructor.name_no_title >}}]({{< var instructor.url >}})]{.ms-1}
* {{< fa sharp envelope title="Email" >}} [[{{< var instructor.email >}}](mailto:{{< var instructor.email >}})]{.ms-1}
* {{< fa sharp building title="Office" >}} [{{< var instructor.office >}}]{.ms-2}
:::

::: {.column width="30%"}
### TA

* {{< fa sharp user title="Name" >}} [[{{< var ta.name_no_title >}}]({{< var ta.url >}})]{.ms-1}
* {{< fa sharp envelope title="Email" >}} [[{{< var ta.email >}}](mailto:{{< var ta.email >}})]{.ms-1}
* {{< fa sharp building title="Office" >}} [{{< var ta.office >}}]{.ms-2}
::::

::: {.column width="30%"}
### Meetings

* {{< fa sharp calendar title="Class Days" >}} {{< var course.days >}}
* {{< fa sharp clock title="Class Time" >}} {{< var course.time >}}
* {{< fa sharp university title="Class Location" >}} {{< var course.location >}}
:::

::::

### Learning Objectives

At the end of this class, students will:

1. Construct mathematical models for climate hazards;
1. Use reproducible software tools to implement mathematical models;
1. Use Bayesian and maximum likelihood methods to conduct statistical inference ("inverse modeling");
1. Use simulation models ("forward modeling") to assess the logical implications of different mathematical models;
1. Understand and apply extreme value theory to estimate the probability of rare climate hazards;
5. Identify the assumptions that commonly applied data science methods make, and describe where they are or are not appropriate to particular problems;
6. Critically interpret statistical analyses of environmental data applied in academic journals, government, and industry; and
1. Understand and communicate subjective modeling choices to technical (e.g., scientist) and non-technical (e.g., policy-maker) audiences.

### Prerequisites & Preparation

The following courses/material would be ideal preparation:

* A course in applied statistics (e.g., STAT 419/519) is strongly encouraged
* Experience in Python, Julia, Matlab, R, or a similar language is strongly encouraged
* Prior exposure to machine learning, Bayesian statistics, or similar is helpful but not required

If you are unsure whether your background gives you an adequate preparation for this course, please contact the instructor!
*Put `[CEVE 543]` in the subject line of your email.*

::: {.callout-tip}
### What If My Programming or Stats Skills Are Rusty?

If your programming or statistics skills are a little rusty, don't worry! We will review concepts and build skills as needed.
:::

### Topics

The course will build core skills in:

:::: {.columns}
::: {.column width="48%"}
* Statistical inference
* Machine learning
* Data wrangling and visualization
* Extreme value analysis
* Model selection, validation, and comparison
:::

::: {.column width="4%"}
:::

::: {.column width="48%"}
We will apply these methods to a wide range of case studies, including three project-based assignments that cover:

* Precipitation frequency analysis
* Flood extent estimation
* Stochastic streamflow generation
:::
::::

For details, see the [schedule](./schedule.qmd).

## A Community of Learning

Rice's [core values](https://www.rice.edu/mission-values) are responsibility, integrity, community, and excellence.
Our goal is to create a learning community aligned with these core values.

### Core Expectations

Course success involves a dual responsibility on the part of the instructor and the student.

:::: {.columns}

::: {.column width="48%"}
As the instructor, my responsibility is to provide you with a structure and opportunity to learn.
To this end, I commit to:

* provide organized and focused lectures, in-class activities, and assignments;
* encourage students to regularly evaluate and provide feedback on the course;
* manage the classroom atmosphere to promote learning;
* schedule sufficient out-of-class contact opportunities, such as office hours;
* allow adequate time for assignment completion;
* make lecture materials, class policies, activities, and assignments accessible to students. 
:::

::: {.column width="4%"}
:::

::: {.column width="48%"}
Students are responsible for their own learning in the course and should commit to:

* attending all lectures;
* doing all required preparatory work before class; 
* actively participating in online and in-class discussions;
* beginning assignments and other work early; and
* attending office hours as needed. 
:::

::::

::: {.callout-important}
## What If I'm Sick?

Please stay home if you're feeling sick!
This is beneficial for both for your own recovery and the health and safety of your classmates.
We will also make any necessary arrangements for you to stay on top of the class material and if whatever is going on will negatively impact your grade, for example by causing you to be unable to submit an assignment on time.
:::

::: {.callout-important}
## Canvas Discussions

* If you wait until the day an assignment is due (or even late the previous night) to ask a question on Canvas, there is a strong chance that I will not see your post prior to the deadline. 
* But if you see unanswered questions and you have some insight, please answer! This class will work best when we all work together as a community.
:::

### Diversity, Equity, and Inclusion

Rice is committed to building and maintaining an equitable and inclusive campus community.
Diversity can refer to multiple ways that we identify ourselves, including but not limited to race, color, national origin, language, sex, disability, age, sexual orientation, gender identity, religion, creed, ancestry, belief, veteran status, or genetic information.
Each of these diverse identities, along with many others not mentioned here, shape the perspectives our students, faculty, and staff bring to our campus.
We, at Rice, will work to promote diversity, equity and inclusion not only because diversity fuels excellence and innovation, but because we want to pursue justice.
We acknowledge our imperfections while we also fully commit to the work, inside and outside of our classrooms, of building and sustaining a campus community that increasingly embraces these core values.

Each of us is responsible for creating a safer, more inclusive environment.y.

### Accommodation for Students with Disabilities

If you have a documented disability or other condition that may affect academic performance you should: 1) make sure this documentation is on file with the Disability Resource Center (Allen Center, Room 111 / [adarice@rice.edu](mailto:adarice@rice.edu) / x5841) to determine the accommodations you need; and 2) talk with me to discuss your accommodation needs.

### Accommodation for Scheduling Conflicts

If any of our class meetings conflict with your religious events, student athletics, or other non-negotiable scheduling conflict, please let me know ASAP so that we can make arrangements for you.

### Mask Policies

Masks are welcome but not required in the classroom.
However, I *strongly encourage* compliance with requests to mask from students, faculty, and staff who are concerned about the risk of infection.
Please be respectful of these concerns and requests and do not ask someone making such a request to disclose their underlying medical condition.
If for some reason you need your instructor or classmates to wear a mask, please let me know and I will communicate this to the class without disclosing your identity.

These policies may change over the course of the semester as the situation evolves.

### Policy on Web Posting of Course Materials

Uploading course materials to web sites is not an authorized use of the course material.
Both the poster and the user are in violation of the university policy, which is actionable.

### Academic Integrity

This class is designed to encourage collaboration, and students are encouraged to discuss their work with other students.
Engineering as a profession relies upon the honesty and integrity of its practitioners (see *e.g.* the [American Society for Civil Engineers' Code of Ethics](https://www.asce.org/-/media/asce-images-and-files/career-and-growth/ethics/documents/asce-code-ethics.pdf)).
**All work submitted must represent the students' own work and understanding**, whether individually or as a group (depending on the particulars of the assignment).
This includes analyses,  code,  software  runs,  and  reports.

More specifically, all students will be held to the standards of the Rice Honor Code, a code that you pledged to honor when you matriculated at this institution.
If you are unfamiliar with the details of this code and how it is administered, you should consult the Honor System Handbook at [honor.rice.edu/honor-system-handbook/](https://honor.rice.edu/honor-system-handbook/).
This handbook outlines the University's expectations for the integrity of your academic work, the procedures for resolving alleged violations of those expectations, and the rights and responsibilities of students and faculty members throughout the process.

If you are ever unclear about academic integrity, please ask!
Additionally, always err on the side of providing more information.)

### AI/ML Resource Policy

AI/ML tools, like ChatGPT, can be incredibly powerful aids in learning, and can help beginner programmers with syntax and code structure.
However, the use of these tools poses risks including the potential for plagiarism and the potential for students to rely on these tools without developing their own understanding.

As noted, all work submitted for a grade in this course must reflect your own understanding.
You are welcome to use AI/ML tools to help you learn, but you *must* describe how you used the tool when you turn in your assignment.
Moreover, you should not submit code that you do not understand as you be held responsible for explaining any code you submit.

### Late Work Policy

Late projects will be subjected to a 10% penalty per day, *which can accumulate to 100% of the total grade*.
Late homework and labs will not be accepted, because we will discuss the solutions in class.

Sometimes things come up in life.
Please reach out *ahead of time* if you have extenuating circumstances (including University-approved absences or illnesses) which would make it difficult for you to submit your work on time.
Work which would be late for appropriate reasons will be given extensions and the late penalty will be waived.

## Grading

### Lab Notebooks: 10%

Some classes will involve hands-on exercises (which we will call "labs") which will give you guided practice applying the concepts and methods from class.
These labs will be announced on [the course website]({{<var course.url >}}) ahead of time so anyone who is able can bring a laptop to class.
These labs can be done in groups; if you cannot bring a laptop to class for whatever reason, you will be able to (and are encouraged to) work with other students, though you must turn in your own assignment for grading.

Some details on lab logistics:

* Labs will be designed to be completed in class, but you may occasionally require additional time to complete them.
* Rubrics will be provided for lab grading as part of the lab assignments.

### Tests: 40%

In-class written exams will be given for each of the four modules of the course, on the dates listed on the [schedule](./schedule.qmd).
Tests will cover material from lectures and labs, and we will dedicate a class to review before each exam.

### Projects: 40%

The second, third, and fourth modules of the class will culminate with a project.
The goal of these project is to apply the tools we learn in class to a real-world problem.
You can think of these projects as a "mini-capstone" for each module, and should take the time of a long problem set.

Specific instructions and rubrics will be provided for each project.
You will turn in your project as a Quarto notebook (`.qmd` file) and a rendered PDF.
Climate risk analyses are communicated to a wide range of audiences, including a skeptical scientist, a trial lawyer, the manager of a banking risk management team, or an interested policy-maker.
Each project will require you to communicate your results to a different audience, and you will be graded on how well you communicate your results to that audience.

### Participation: 10%

Participating fully in the class allows you to gain more from the class and contribute more to the learning of your classmates.
Some ways to participate include:

- Attending every class
- Asking questions in class
- Answering questions on Canvas
- Coming to office hours

You will be asked to evaluate your own participation over the course of the semester, and I will provide feedback on your participation as well